---
- name: Collect KVM VM information
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Ensure virsh is available
      command: which virsh
      register: virsh_check
      ignore_errors: yes

    - name: Fail if virsh not found
      fail:
        msg: "virsh command not found on {{ inventory_hostname }}"
      when: virsh_check.rc != 0

    - name: Get list of all VMs
      shell: virsh list --all --name
      register: vm_list

    - name: Collect VM details
      when: item != ""
      shell: |
        vm="{{ item }}"
        vcpu=$(virsh dominfo "$vm" | awk -F: '/CPU\(s\)/ {gsub(/ /,"",$2); print $2}')
        ram=$(virsh dominfo "$vm" | awk -F: '/Max memory/ {gsub(/ /,"",$2); print int($2/1024)}')
        disks=$(virsh domblklist "$vm" --details | awk '/disk/ {print $4}' | tr '\n' ';')
        ip=$(virsh domifaddr "$vm" 2>/dev/null | awk '/ipv4/ {print $4}' | cut -d'/' -f1)
        if [ -z "$ip" ]; then ip="N/A"; fi
        echo "$vm,$vcpu,$ram,$disks,$ip"
      loop: "{{ vm_list.stdout_lines }}"
      register: vm_details

    - name: Build VM info lines
      set_fact:
        vm_info_lines: "{{ vm_details.results | map(attribute='stdout') | list }}"

- name: Create CSV on controller
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Build CSV content
      set_fact:
        csv_report: |
          VM Name,vCPU,RAM(MB),Disk(Path),IP Address
          {% for host in groups['all'] %}
          {% if hostvars[host].vm_info_lines is defined %}
          {% for line in hostvars[host].vm_info_lines %}
          {{ line }}
          {% endfor %}
          {% endif %}
          {% endfor %}

    - name: Save CSV file
      copy:
        dest: ./kvm_vm_report.csv
        content: "{{ csv_report }}"

- name: Send VM Report via Email
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Email CSV file
      community.general.mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: m.jahangir.alam@ucb.com.bd
        subject: "KVM VM Info Report"
        body: "Attached is the KVM VM information report."
        attach:
          - "./kvm_vm_report.csv"
