---
- name: Collect KVM VM information
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Get list of all VMs
      shell: virsh list --all --name
      register: vm_list

    - name: Collect VM details
      shell: |
        vm="{{ item }}"
        vcpu=$(virsh dominfo "$vm" | grep 'CPU(s)' | awk '{print $2}')
        ram=$(virsh dominfo "$vm" | grep 'Max memory' | awk '{print $3}')
        storage=$(virsh domblklist "$vm" --details | awk '/disk/ {print $4}')
        ip=$(virsh domifaddr "$vm" | awk '/ipv4/ {print $4}' | cut -d'/' -f1)
        echo "$vm,$vcpu,$ram,$storage,$ip"
      register: vm_details
      loop: "{{ vm_list.stdout_lines }}"
      when: item != ""

    - name: Build VM info lines
      set_fact:
        vm_info_lines: "{{ vm_details.results | map(attribute='stdout') | list }}"

- name: Create CSV on controller
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Build CSV content
      set_fact:
        csv_report: |
          VM Name,vCPU,RAM(MB),Storage Path,IP Address
          {% for host in ansible_play_hosts %}
          {% for line in hostvars[host].vm_info_lines %}
          {{ line }}
          {% endfor %}
          {% endfor %}

    - name: Save CSV file
      copy:
        dest: ./kvm_vm_report.csv
        content: "{{ csv_report }}"

- name: Send VM Report via Email
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Email CSV file
      community.general.mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: m.jahangir.alam@ucb.com.bd
        subject: "KVM VM Info Report"
        body: "Attached is the KVM VM information report."
        attach:
          - "./kvm_vm_report.csv"
